name: publish-dev

on:
  push:
    branches:
      - develop

jobs:
  publish-docker-image-dev:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 16.x
      uses: actions/setup-node@v3
      with:
        node-version: 16.x

    - name: npm install, make test-coverage
      run: |
        npm install
        npm test

    - name: Coveralls
      uses: coverallsapp/github-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build the hello-docker Docker image
      run: |
        docker build . --tag ghcr.io/maxlepan/hello-docker-gcr-demo:staging
        docker push ghcr.io/maxlepan/hello-docker-gcr-demo:staging